import Foundation
import Testing
@testable import TransfrCore

/// The walk-delivery contract (`/walk`, `/walks`): a `WalkResult` envelope
/// wrapping the `VizExport` geometry. Goldens are generated by the same
/// `api/schemas.py` models the endpoints serve (see `generate_fixtures.py`), so
/// a server-side envelope change fails a decode here immediately.
struct WalkDecodeTests {

    static func fixture(_ name: String) throws -> Data {
        let url = try #require(
            Bundle.module.url(forResource: "Fixtures/\(name)", withExtension: "json"),
            "missing fixture \(name).json"
        )
        return try Data(contentsOf: url)
    }

    // MARK: - /walk

    @Test func decodesSingleWalkWithNestedExport() throws {
        let r = try TransfrJSON.decode(WalkResult.self, from: Self.fixture("walk_single"))
        #expect(r.ok)
        #expect(r.reason == nil)
        // The envelope's key fields survived snake_case → camelCase.
        #expect(r.relationId == 5688517)
        #expect(r.fromPlatform == "1")
        #expect(r.toPlatform == "2")
        // …and the nested VizExport decoded through the envelope.
        let export = try #require(r.export)
        #expect(export.path.found)
        #expect((export.path.walkingTimeSeconds ?? 0) > 0)
        #expect(!export.ways.isEmpty)
    }

    @Test func decodesBoardingGuidanceOnWalk() throws {
        let r = try TransfrJSON.decode(WalkResult.self, from: Self.fixture("walk_single"))
        let b = try #require(r.boarding)
        #expect(b.arrivalPlatform == "1")
        #expect(b.departurePlatform == "2")
        #expect(b.hasPosition)                 // a real 430 m edge was measured
        #expect(b.stepoffFraction == 1.0)      // step off at the cross-over end
        #expect(b.timeSavedS > 40)
        #expect(b.band == .high)
        // Position is known; the coach needs a live formation feed we don't have.
        #expect(b.coach == nil)
        #expect(b.reason == "no_formation_feed")
    }

    // MARK: - /walks (batch)

    @Test func decodesBatchWithFoundAndFailedKeys() throws {
        let resp = try TransfrJSON.decode(WalksResponse.self, from: Self.fixture("walks_batch"))
        #expect(resp.walks.count == 2)

        let ok = resp.walks[0]
        #expect(ok.ok)
        #expect(ok.export != nil)

        // A key that produced no geometry: ok=false, reason set, export nil —
        // the client shows the transfer without a walk rather than crashing.
        let failed = resp.walks[1]
        #expect(!failed.ok)
        #expect(failed.reason == "no_geometry_for_platforms")
        #expect(failed.export == nil)
    }

    // MARK: - WalkKey derivation & request encoding

    @Test func walkKeyBuildsFromResolvedTransfer() throws {
        let j = try #require(
            try TransfrJSON.decode(JourneysResponse.self,
                                   from: Self.fixture("journeys_hamburg_stuttgart")).journeys.first
        )
        // Mannheim transfer resolved a relation + both platforms → a fetchable key.
        let mannheim = j.transfers[1]
        let key = try #require(WalkKey(transfer: mannheim))
        #expect(key.relationId == mannheim.relationId)
        #expect(key.fromPlatform == mannheim.arrivalPlatform)   // arrival = walk start
        #expect(key.toPlatform == mannheim.departurePlatform)   // departure = walk end
        #expect(!key.stepFree)
    }

    @Test func walkKeyIsNilForUnresolvedTransfer() {
        // No relation / platforms (e.g. a no_platform_data transfer) ⇒ no walk.
        let t = Transfer(atStation: "X", relationId: nil, arrivalPlatform: nil,
                         departurePlatform: nil, layoverS: nil, walkTimeS: nil,
                         walkDistanceM: nil, verdict: "unknown", reason: "no_platform_data")
        #expect(WalkKey(transfer: t) == nil)
    }

    @Test func walksRequestEncodesSnakeCaseForServer() throws {
        let req = WalksRequest(keys: [WalkKey(relationId: 42, fromPlatform: "4",
                                              toPlatform: "5", stepFree: true)])
        let data = try TransfrJSON.encoder.encode(req)
        let wire = try #require(String(data: data, encoding: .utf8))
        // The server's WalkKey expects snake_case; the shared encoder must produce it.
        #expect(wire.contains("relation_id"))
        #expect(wire.contains("from_platform"))
        #expect(wire.contains("step_free"))
        // Round-trips back through the server-shaped decoder.
        let back = try TransfrJSON.decode(WalksRequest.self, from: data)
        #expect(back.keys.first?.relationId == 42)
        #expect(back.keys.first?.stepFree == true)
    }
}
